# Generated by Django 3.1.3 on 2020-11-12 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoURL', models.URLField(blank=True)),
                ('about', models.TextField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoURL', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('music', 'music'), ('food', 'food'), ('film', 'film'), ('travel', 'travel'), ('culture', 'culture'), ('drinks', 'drinks'), ('unknown', 'unknown')], default='unknown', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=150)),
                ('venue_lat', models.FloatField(default=0)),
                ('venue_lng', models.FloatField(default=0)),
                ('ticket_price', models.PositiveIntegerField(default=0)),
                ('going', models.ManyToManyField(related_name='going', to='events.Profile')),
                ('hosted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.profile')),
                ('interested', models.ManyToManyField(related_name='interested', to='events.Profile')),
                ('likes', models.ManyToManyField(related_name='like', to='events.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
                ('created_at', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.event')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='events.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
