# Generated by Django 3.1.3 on 2020-11-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0002_auto_20201113_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='going',
            field=models.ManyToManyField(related_name='going', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hosted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='interested',
            field=models.ManyToManyField(related_name='interested', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='likes',
            field=models.ManyToManyField(related_name='like', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
