# Generated by Django 3.1.3 on 2020-11-27 14:04

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201124_1502'),
        ('events', '0003_auto_20201120_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='likes',
        ),
        migrations.AddField(
            model_name='event',
            name='event_photo',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventPhoto',
        ),
        migrations.AddField(
            model_name='eventlikes',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='eventlikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
