# Generated by Django 3.1.3 on 2020-11-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201124_1502'),
        ('events', '0004_auto_20201127_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventLikes',
            new_name='Like',
        ),
    ]
