# Generated by Django 3.1.3 on 2020-12-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20201130_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('MUSIC', 'music'), ('FOOD', 'food'), ('FUN', 'fun'), ('FILM', 'film'), ('TRAVEL', 'travel'), ('CULTURE', 'culture'), ('DRINKS', 'drinks'), ('UNKNOWN', 'unknown')], default='unknown', max_length=100),
        ),
    ]
